# Generated by Django 2.0.4 on 2018-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180430_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcemember',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='datasourcemember',
            name='token_expires',
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-04-23 17:34:48+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-04-23 17:34:48+00:00'),
        ),
    ]
